### ISSUE TITLE
Error: set width must be lower than terminal width

### ISSUE THREAD

**Issue by fuelen** [samodostal/image.nvim#3]
when I open any image I see this error instead of ascii graphics:
```
                 Error: set width must be lower than terminal width
 ```

**Comment by max397574** [comment]
what was the width of your terminal?

**Comment by fuelen** [comment]
```
$ tput cols
190
```
```
$ tput lines
45
```

**Comment by LemonjamesD** [comment]
This also doesn't work with [neovide](https://github.com/neovide/neovide)
```
$ tput cols
2
$ tput lines
2
```

**Comment by Curs3W4ll** [comment]
Same error for me.

I'm using terminator as terminal

Whatever the size of my terminal is (even if a spam `CTRL+-`), the same error appears

**Comment by TheZoraiz** [comment]
This issue was resolved with ascii-image-converter version `v1.11.0`. Please ensure you have at least that version or higher.

**Comment by fuelen** [comment]
I've updated to `v1.13.0-1` and now I just have an empty screen when I open an image

**Comment by fuelen** [comment]
Will track https://github.com/samodostal/image.nvim/issues/8 for empty screen

**Comment by samodostal** [comment]
@TheZoraiz do you know if the latest version of your package could cause #8?

**Comment by TheZoraiz** [comment]
The latest version comes with bin piping support for cli. I suppose I was lax on the error handling if it's just showing an empty screen lol. Looking into this.

**Comment by samodostal** [comment]
So should the package be used in a different way now? Probably it's not your error handling fault but mine, I don't think I handle any error messages coming from your package

**Comment by TheZoraiz** [comment]
The usage should remain the same (at least that was the intention, didn't want to break anything lol).

It's supposed to detect piped `stdin` and treat it as binary input instead of a file path (file path is basically ignored in that case). So maybe it's messing up there in neovim.

I'm unfamiliar with neovim or vim to begin with, so might need some time get to the bottom of this. Meanwhile, you can perhaps specify ascii-image-converter `v1.12.0` in the README.
